work_dir: 'grabnet/results'
base_lr: 0.0005
batch_size: 625
best_cnet: '/data/3D_dataset/hand_grasp/GrabNet/grabnet/models/coarsenet.pt'
best_rnet: '/data/3D_dataset/hand_grasp/GrabNet/grabnet/models/refinenet.pt'
bps_size: 4096
cuda_id: 0
expr_ID: 'V00'
kl_coef: 0.005
latentD: 16
log_every_epoch: 2
n_epochs: 500
n_neurons: 512
n_workers: 10
reg_coef: 0.0005
rhm_path: '/data/3D_dataset/smpl_related/models/mano/'
seed: 4815
try_num: 0
use_multigpu: False
load_on_ram: False